/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/register': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['RegisterRequest']
          'text/json': components['schemas']['RegisterRequest']
          'application/*+json': components['schemas']['RegisterRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserDto']
            'application/json': components['schemas']['UserDto']
            'text/json': components['schemas']['UserDto']
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDto']
            'application/json': components['schemas']['ValidationProblemDto']
            'text/json': components['schemas']['ValidationProblemDto']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest']
          'text/json': components['schemas']['LoginRequest']
          'application/*+json': components['schemas']['LoginRequest']
        }
      }
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDto']
            'application/json': components['schemas']['ValidationProblemDto']
            'text/json': components['schemas']['ValidationProblemDto']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['UserDto']
            'application/json': components['schemas']['UserDto']
            'text/json': components['schemas']['UserDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/auth/antiforgery': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/items/all': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['AllItemDto'][]
            'application/json': components['schemas']['AllItemDto'][]
            'text/json': components['schemas']['AllItemDto'][]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/leagues': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['LeagueDto'][]
            'application/json': components['schemas']['LeagueDto'][]
            'text/json': components['schemas']['LeagueDto'][]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateLeagueRequest']
          'text/json': components['schemas']['CreateLeagueRequest']
          'application/*+json': components['schemas']['CreateLeagueRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['LeagueDto']
            'application/json': components['schemas']['LeagueDto']
            'text/json': components['schemas']['LeagueDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDto']
            'application/json': components['schemas']['ValidationProblemDto']
            'text/json': components['schemas']['ValidationProblemDto']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/leagues/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['LeagueDto']
            'application/json': components['schemas']['LeagueDto']
            'text/json': components['schemas']['LeagueDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateLeagueRequest']
          'text/json': components['schemas']['UpdateLeagueRequest']
          'application/*+json': components['schemas']['UpdateLeagueRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['LeagueDto']
            'application/json': components['schemas']['LeagueDto']
            'text/json': components['schemas']['LeagueDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDto']
            'application/json': components['schemas']['ValidationProblemDto']
            'text/json': components['schemas']['ValidationProblemDto']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/teams': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TeamDto'][]
            'application/json': components['schemas']['TeamDto'][]
            'text/json': components['schemas']['TeamDto'][]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateTeamRequest']
          'text/json': components['schemas']['CreateTeamRequest']
          'application/*+json': components['schemas']['CreateTeamRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TeamDto']
            'application/json': components['schemas']['TeamDto']
            'text/json': components['schemas']['TeamDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDto']
            'application/json': components['schemas']['ValidationProblemDto']
            'text/json': components['schemas']['ValidationProblemDto']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/teams/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TeamDto']
            'application/json': components['schemas']['TeamDto']
            'text/json': components['schemas']['TeamDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateTeamRequest']
          'text/json': components['schemas']['UpdateTeamRequest']
          'application/*+json': components['schemas']['UpdateTeamRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['TeamDto']
            'application/json': components['schemas']['TeamDto']
            'text/json': components['schemas']['TeamDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDto']
            'application/json': components['schemas']['ValidationProblemDto']
            'text/json': components['schemas']['ValidationProblemDto']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/volunteers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['VolunteerDto'][]
            'application/json': components['schemas']['VolunteerDto'][]
            'text/json': components['schemas']['VolunteerDto'][]
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
      }
    }
    put?: never
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateVolunteerRequest']
          'text/json': components['schemas']['CreateVolunteerRequest']
          'application/*+json': components['schemas']['CreateVolunteerRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['VolunteerDto']
            'application/json': components['schemas']['VolunteerDto']
            'text/json': components['schemas']['VolunteerDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDto']
            'application/json': components['schemas']['ValidationProblemDto']
            'text/json': components['schemas']['ValidationProblemDto']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/volunteers/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['VolunteerDto']
            'application/json': components['schemas']['VolunteerDto']
            'text/json': components['schemas']['VolunteerDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
      }
    }
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateVolunteerRequest']
          'text/json': components['schemas']['UpdateVolunteerRequest']
          'application/*+json': components['schemas']['UpdateVolunteerRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['VolunteerDto']
            'application/json': components['schemas']['VolunteerDto']
            'text/json': components['schemas']['VolunteerDto']
          }
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ValidationProblemDto']
            'application/json': components['schemas']['ValidationProblemDto']
            'text/json': components['schemas']['ValidationProblemDto']
          }
        }
      }
    }
    post?: never
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['ProblemDetails']
            'application/json': components['schemas']['ProblemDetails']
            'text/json': components['schemas']['ProblemDetails']
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'text/plain': components['schemas']['MessageDto']
            'application/json': components['schemas']['MessageDto']
            'text/json': components['schemas']['MessageDto']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AllItemDto: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      listId?: string
      listName?: string
      scopeType?: string
      scopeName?: null | string
      title?: string
      description?: null | string
      /** Format: date */
      dueDate?: null | string
    }
    CreateLeagueRequest: {
      name?: null | string
    }
    CreateTeamRequest: {
      name?: null | string
      /** Format: uuid */
      leagueId?: null | string
    }
    CreateVolunteerRequest: {
      name?: null | string
      /** Format: uuid */
      leagueId?: null | string
      teamIds?: null | string[]
    }
    LeagueDto: {
      /** Format: uuid */
      id?: string
      name?: string
    }
    LoginRequest: {
      email?: string
      password?: string
    }
    MessageDto: {
      message?: string
    }
    ProblemDetails: {
      type?: null | string
      title?: null | string
      /** Format: int32 */
      status?: null | number | string
      detail?: null | string
      instance?: null | string
    }
    RegisterRequest: {
      email?: string
      password?: string
    }
    TeamDto: {
      /** Format: uuid */
      id?: string
      name?: string
      /** Format: uuid */
      leagueId?: null | string
    }
    UpdateLeagueRequest: {
      name?: null | string
    }
    UpdateTeamRequest: {
      name?: null | string
      /** Format: uuid */
      leagueId?: null | string
    }
    UpdateVolunteerRequest: {
      name?: null | string
      /** Format: uuid */
      leagueId?: null | string
      teamIds?: null | string[]
    }
    UserDto: {
      /** Format: uuid */
      id?: string
      email?: string
    }
    ValidationErrorDto: {
      property?: null | string
      message?: string
    }
    ValidationProblemDto: {
      id?: string
      message?: string
      errors?: components['schemas']['ValidationErrorDto'][]
      warnings?: components['schemas']['ValidationErrorDto'][]
    }
    VolunteerDto: {
      /** Format: uuid */
      id?: string
      name?: string
      /** Format: uuid */
      leagueId?: null | string
      teamIds?: string[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
